// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "easterEgg":return img`
................
................
................
................
.......ff.......
....bbbbbbbb....
....bffffffb....
....bf2ff2fb....
....bf2ff2fb....
....bffffffb....
....bffffffb....
....bbbbbbbb....
...bffffffffb...
...bffffffffb...
..fbff2ff2ffbf..
.f.bffffffffb.f.
.f.bffffffffb.f.
.f.bff2ff2ffb.f.
.f.bffffffffb.f.
.f.bffffffffb.f.
...bff2222ffb...
...bffffffffb...
...bffffffffb...
...bbbbbbbbbb...
.....f....f.....
.....f....f.....
.....f....f.....
.....f....f.....
....fff..fff....
....fff..fff....
................
................
`;
            case "image2":
            case "Temporary asset0":return img`
................
................
................
................
.......ff.......
....bbbbbbbb....
....bffffffb....
....bf8ff8fb....
....bf8ff8fb....
....bffffffb....
....bffffffb....
....bbbbbbbb....
...bffffffffb...
...bffffffffb...
..fbffcffcffbf..
.f.bffffffffb.f.
.f.bffffffffb.f.
.f.bffcffcffb.f.
.f.bffffffffb.f.
.f.bffffffffb.f.
...bffcffcffb...
...bffffffffb...
...bffffffffb...
...bbbbbbbbbb...
.....f....f.....
.....f....f.....
.....f....f.....
.....f....f.....
....fff..fff....
....fff..fff....
................
................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
